"""Encoding a freshly built ``Placement`` -- the direction the tool exists for.

The round-trip tests prove we can reproduce the game's bytes.  These prove we
can *originate* bytes the game will accept.
"""

from __future__ import annotations

import dataclasses
from fractions import Fraction
from typing import cast

import pytest

from flab2bp.dsp.codec import decode, encode, encode_blueprint, placement_to_blueprint
from flab2bp.dsp.envelope import BlueprintFormatError, dotnet_ticks
from flab2bp.layout.base import AreaFrame, PlacedBuilding, Placement, PlacementStats

from .conftest import fixture_texts

BELT_MK2 = 2002
BELT_MK2_MODEL = 36
SORTER_MK1 = 2011
SORTER_MK1_MODEL = 41
SMELTER = 2302
SMELTER_MODEL = 62


def _tiny_placement() -> Placement:
    """A smelter, a sorter and two belt tiles -- one of every record class."""
    return Placement(
        buildings=(
            PlacedBuilding(
                item_id=SMELTER,
                model_index=SMELTER_MODEL,
                x=0,
                y=0,
                width=3,
                height=3,
                recipe_id=61,
            ),
            PlacedBuilding(
                item_id=SORTER_MK1,
                model_index=SORTER_MK1_MODEL,
                x=3,
                y=1,
                x2=4,
                y2=1,
                z2=Fraction(0),
                yaw=90.0,
                input_obj=0,
                output_obj=2,
            ),
            PlacedBuilding(
                item_id=BELT_MK2,
                model_index=BELT_MK2_MODEL,
                x=4,
                y=1,
                output_obj=3,
            ),
            PlacedBuilding(
                item_id=BELT_MK2,
                model_index=BELT_MK2_MODEL,
                x=5,
                y=1,
            ),
        ),
        short_desc="tiny",
        description="generated by flab2bp",
        icons=(SMELTER,),
        frame=AreaFrame(6, 3, 4, (4,), False),
    )


def test_encoded_placement_decodes_again() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    assert text.startswith("BLUEPRINT:")
    bp = decode(text)
    assert len(bp.buildings) == 4


def test_encoded_placement_has_a_valid_hash() -> None:
    """A wrong hash is the failure mode the game rejects outright."""
    assert decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0))).hash_valid


def test_encoding_is_deterministic() -> None:
    a = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    b = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    assert a == b


def test_connections_survive_encoding() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    sorter = bp.buildings[1]
    assert sorter.input_obj_idx == 0
    assert sorter.output_obj_idx == 2
    # An unconnected end is -1, not 0, which would wrongly name building zero.
    assert bp.buildings[3].output_obj_idx == -1


def test_recipe_survives_encoding() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    assert bp.buildings[0].recipe_id == 61


def test_area_covers_the_placement() -> None:
    bp = placement_to_blueprint(_tiny_placement())
    area = bp.areas[0]
    assert (area.width, area.height) == (6, 3)


def test_empty_placement_is_encodable() -> None:
    placement = Placement(buildings=(), frame=AreaFrame(1, 1, 4, (4,), False))
    text = encode(placement, timestamp=dotnet_ticks(0))
    assert decode(text).buildings == ()


def test_unfinalized_placement_is_not_encoded_even_with_legacy_stats() -> None:
    legacy_stats = cast(
        PlacementStats,
        cast(object, {"area_segments": 40.0, "band_rotated": 0.0}),
    )
    with pytest.raises(ValueError, match="area frame"):
        placement_to_blueprint(Placement(buildings=(), stats=legacy_stats))


def test_encoder_reads_dimensions_and_band_only_from_frame() -> None:
    legacy_stats = cast(
        PlacementStats,
        cast(object, {"area_segments": 200.0, "band_rotated": 1.0}),
    )
    placement = Placement(
        buildings=(PlacedBuilding(item_id=BELT_MK2, model_index=BELT_MK2_MODEL, x=0, y=0),),
        stats=legacy_stats,
        frame=AreaFrame(12, 7, 40, (40, 60, 80), False),
    )

    area = placement_to_blueprint(placement).areas[0]

    assert (area.width, area.height, area.area_segments) == (12, 7, 40)


def test_encoder_refuses_a_footprint_outside_the_frame() -> None:
    placement = Placement(
        buildings=(
            PlacedBuilding(
                item_id=SMELTER,
                model_index=SMELTER_MODEL,
                x=1,
                y=0,
                width=2,
                height=1,
            ),
        ),
        frame=AreaFrame(2, 1, 4, (4,), False),
    )

    with pytest.raises(ValueError, match="footprint"):
        placement_to_blueprint(placement)


def test_encoder_refuses_a_second_anchor_outside_the_frame() -> None:
    placement = Placement(
        buildings=(
            PlacedBuilding(
                item_id=SORTER_MK1,
                model_index=SORTER_MK1_MODEL,
                x=0,
                y=0,
                x2=2,
                y2=0,
            ),
        ),
        frame=AreaFrame(2, 1, 4, (4,), False),
    )

    with pytest.raises(ValueError, match="second anchor"):
        placement_to_blueprint(placement)


def test_encoder_refuses_a_frame_that_names_no_band() -> None:
    placement = Placement(
        buildings=(),
        frame=AreaFrame(1, 1, 240, (240,), False),
    )

    with pytest.raises(ValueError, match="no DSP latitude band"):
        placement_to_blueprint(placement)


def test_encoder_refuses_a_frame_that_does_not_fit_its_primary_band() -> None:
    placement = Placement(
        buildings=(),
        frame=AreaFrame(21, 1, 4, (4,), False),
    )

    with pytest.raises(ValueError, match="does not fit"):
        placement_to_blueprint(placement)


def test_description_reaches_the_header() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    assert bp.header.description == "generated by flab2bp"
    assert bp.header.short_desc == "tiny"


def test_description_with_special_characters_survives() -> None:
    p = dataclasses.replace(_tiny_placement(), description="60/min, 100% ratio & spray")
    bp = decode(encode(p, timestamp=dotnet_ticks(0)))
    assert bp.header.description == "60/min, 100% ratio & spray"


@pytest.mark.parametrize("name,text", fixture_texts(include_dyson=False)[:3])
def test_roundtrip_detects_a_mutated_building(name: str, text: str) -> None:
    """Guards the round-trip suite itself against being vacuously true."""
    bp = decode(text)
    mutated = dataclasses.replace(
        bp,
        buildings=(dataclasses.replace(bp.buildings[0], x=bp.buildings[0].x + 1.0),)
        + bp.buildings[1:],
    )
    assert encode_blueprint(mutated) != text


def test_reserved_header_cell_is_zero() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    cells = text[len("BLUEPRINT:") : text.index('"')].split(",")
    assert cells[7] == "0"


def test_truncated_string_is_rejected() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    with pytest.raises(BlueprintFormatError):
        decode(text[: text.index('"') + 20])
