"""Encoding a freshly built ``Placement`` -- the direction the tool exists for.

The round-trip tests prove we can reproduce the game's bytes.  These prove we
can *originate* bytes the game will accept.
"""

from __future__ import annotations

import dataclasses

import pytest

from flab2bp.dsp.codec import decode, encode, encode_blueprint, placement_to_blueprint
from flab2bp.dsp.envelope import BlueprintFormatError, dotnet_ticks
from flab2bp.layout.base import PlacedBuilding, Placement

from .conftest import fixture_texts

BELT_MK2 = 2002
BELT_MK2_MODEL = 36
SORTER_MK1 = 2011
SORTER_MK1_MODEL = 41
SMELTER = 2302
SMELTER_MODEL = 62


def _tiny_placement() -> Placement:
    """A smelter, a sorter and two belt tiles -- one of every record class."""
    return Placement(
        buildings=(
            PlacedBuilding(
                item_id=SMELTER,
                model_index=SMELTER_MODEL,
                x=0,
                y=0,
                width=3,
                height=3,
                recipe_id=61,
            ),
            PlacedBuilding(
                item_id=SORTER_MK1,
                model_index=SORTER_MK1_MODEL,
                x=3,
                y=1,
                x2=4,
                y2=1,
                z2=0,
                yaw=90.0,
                input_obj=0,
                output_obj=2,
            ),
            PlacedBuilding(item_id=BELT_MK2, model_index=BELT_MK2_MODEL, x=4, y=1, output_obj=3),
            PlacedBuilding(item_id=BELT_MK2, model_index=BELT_MK2_MODEL, x=5, y=1),
        ),
        short_desc="tiny",
        description="generated by flab2bp",
        icons=(SMELTER,),
    )


def test_encoded_placement_decodes_again() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    assert text.startswith("BLUEPRINT:")
    bp = decode(text)
    assert len(bp.buildings) == 4


def test_encoded_placement_has_a_valid_hash() -> None:
    """A wrong hash is the failure mode the game rejects outright."""
    assert decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0))).hash_valid


def test_encoding_is_deterministic() -> None:
    a = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    b = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    assert a == b


def test_connections_survive_encoding() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    sorter = bp.buildings[1]
    assert sorter.input_obj_idx == 0
    assert sorter.output_obj_idx == 2
    # An unconnected end is -1, not 0, which would wrongly name building zero.
    assert bp.buildings[3].output_obj_idx == -1


def test_recipe_survives_encoding() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    assert bp.buildings[0].recipe_id == 61


def test_area_covers_the_placement() -> None:
    bp = placement_to_blueprint(_tiny_placement())
    area = bp.areas[0]
    assert (area.width, area.height) == (6, 3)


def test_empty_placement_is_encodable() -> None:
    text = encode(Placement(buildings=()), timestamp=dotnet_ticks(0))
    assert decode(text).buildings == ()


def test_description_reaches_the_header() -> None:
    bp = decode(encode(_tiny_placement(), timestamp=dotnet_ticks(0)))
    assert bp.header.description == "generated by flab2bp"
    assert bp.header.short_desc == "tiny"


def test_description_with_special_characters_survives() -> None:
    p = dataclasses.replace(_tiny_placement(), description="60/min, 100% ratio & spray")
    bp = decode(encode(p, timestamp=dotnet_ticks(0)))
    assert bp.header.description == "60/min, 100% ratio & spray"


@pytest.mark.parametrize("name,text", fixture_texts(include_dyson=False)[:3])
def test_roundtrip_detects_a_mutated_building(name: str, text: str) -> None:
    """Guards the round-trip suite itself against being vacuously true."""
    bp = decode(text)
    mutated = dataclasses.replace(
        bp,
        buildings=(dataclasses.replace(bp.buildings[0], x=bp.buildings[0].x + 1.0),)
        + bp.buildings[1:],
    )
    assert encode_blueprint(mutated) != text


def test_reserved_header_cell_is_zero() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    cells = text[len("BLUEPRINT:") : text.index('"')].split(",")
    assert cells[7] == "0"


def test_truncated_string_is_rejected() -> None:
    text = encode(_tiny_placement(), timestamp=dotnet_ticks(0))
    with pytest.raises(BlueprintFormatError):
        decode(text[: text.index('"') + 20])
