from array import array

def decode_score(
    positive: array[int],
    negative: array[int],
    east: array[int],
    north: array[int],
    sizes: array[int],
    nets: array[int],
    weights: array[float],
    history: array[float],
    targets: array[int],
    negative_position: array[int],
    horizontal: bytearray,
    vertical: bytearray,
    earliest_x: array[int],
    earliest_y: array[int],
    latest_x: array[int],
    latest_y: array[int],
    outline_height: int,
    history_width: int,
    sorter_max_reach: int,
) -> tuple[
    array[int],
    array[int],
    array[int],
    array[int],
    int,
    int,
    int,
    int,
    float,
    float,
    int,
    int,
]: ...
