"""Consumed CaDiCaL 1.9.5 API from the pinned python-sat 1.9.dev5 package."""

from collections.abc import Iterable, Mapping
from types import TracebackType
from typing import Literal, Self, overload

type _AtMost = tuple[Iterable[int], int] | tuple[Iterable[int], int, Iterable[int]]

class Cadical195:
    def __init__(
        self,
        bootstrap_with: Iterable[Iterable[int] | _AtMost] | None = None,
        use_timer: bool = False,
        incr: bool = False,
        with_proof: bool = False,
        warm_start: bool = False,
        native_card: bool = False,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def configure(self, parameters: Mapping[str, int]) -> None: ...
    def set_phases(self, literals: Iterable[int] = ()) -> None: ...
    def conf_budget(self, budget: int) -> None: ...
    def dec_budget(self, budget: int) -> None: ...
    def solve(self, assumptions: Iterable[int] = ()) -> bool | None: ...
    def solve_limited(
        self, assumptions: Iterable[int] = (), expect_interrupt: bool = False
    ) -> bool | None: ...
    def get_model(self) -> list[int] | None: ...
    def get_core(self) -> list[int] | None: ...
    @overload
    def add_clause(self, clause: Iterable[int], no_return: Literal[True] = True) -> None: ...
    @overload
    def add_clause(self, clause: Iterable[int], no_return: Literal[False]) -> bool | None: ...
    @overload
    def add_clause(self, clause: Iterable[int], no_return: bool) -> bool | None: ...
