"""Render the trunk A/B tables from the harness JSON rows."""

from __future__ import annotations

import glob
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def short_verdict(text: str) -> str:
    if text == "OK":
        return "OK"
    head = text.split("; findings:")[0].split(" (")[0]
    head = re.sub(r"^REFUSED: ", "", head)
    return head[:110]


def stat(row: dict, key: str, default: str = "-") -> str:
    value = row.get("stats", {}).get(key)
    return default if value is None else str(value)


def load(pattern: str) -> dict[tuple[str, str, str], dict]:
    out: dict[tuple[str, str, str], dict] = {}
    for path in sorted(glob.glob(str(HERE / pattern))):
        name = Path(path).stem
        parts = name.rsplit("-", 2)
        if len(parts) == 3 and parts[2].isdigit():
            cell, arm, rnd = parts
        else:
            cell, arm = name.rsplit("-", 1)
            rnd = "1"
        out[cell, arm, rnd] = json.loads(Path(path).read_text())
    return out


def table(rows: dict[tuple[str, str, str], dict], title: str) -> str:
    cells = sorted({key[0] for key in rows})
    rounds = sorted({key[2] for key in rows})
    lines = [
        f"### {title}",
        "",
        "| cell | arm | run | verdict | wall s | route_all s | area | belt tiles | nets | sorters |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cell in cells:
        for arm in ("off", "on"):
            for rnd in rounds:
                row = rows.get((cell, arm, rnd))
                if row is None:
                    continue
                area = row.get("area")
                lines.append(
                    "| {} | {} | {} | {} | {:.1f} | {:.2f} | {} | {} | {} | {} |".format(
                        cell,
                        arm,
                        rnd,
                        short_verdict(row["verdict"]),
                        row["wall_s"],
                        row["route_all_s"],
                        "-" if not area else f"{area:.0f}",
                        stat(row, "belt_tiles"),
                        stat(row, "nets"),
                        stat(row, "sorters"),
                    )
                )
    return "\n".join(lines)


def verdict_counts(rows: dict[tuple[str, str, str], dict]) -> str:
    lines = ["| arm | OK | REFUSED |", "| --- | --- | --- |"]
    for arm in ("off", "on"):
        ok = sum(1 for key, row in rows.items() if key[1] == arm and row["verdict"] == "OK")
        bad = sum(1 for key, row in rows.items() if key[1] == arm and row["verdict"] != "OK")
        lines.append(f"| {arm} | {ok} | {bad} |")
    return "\n".join(lines)


def main() -> int:
    large = load("large/*.json")
    corpus = load("corpus/*.json")
    out = [
        "<!-- generated by analyze.py -->",
        "",
        table(large, "Large cells, budget 60 s, two runs each"),
        "",
        verdict_counts(large),
        "",
        table(corpus, "Corpus cells with the largest max internal spread, freeform 30 s"),
        "",
        verdict_counts(corpus),
        "",
    ]
    text = "\n".join(out)
    (HERE / "tables.md").write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
