# Concrete declarations for the OR-Tools linear solver operations used here.
# The shipped SWIG stubs omit return types on several of these operations.
from collections.abc import Iterable
from typing import ClassVar

class LinearConstraint: ...

class LinearExpr:
    def __add__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __radd__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __sub__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __rsub__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __mul__(self, coefficient: float) -> LinearExpr: ...
    def __rmul__(self, coefficient: float) -> LinearExpr: ...
    def __le__(self, other: LinearExpr | Variable | float) -> LinearConstraint: ...
    def __ge__(self, other: LinearExpr | Variable | float) -> LinearConstraint: ...

class Variable:
    def basis_status(self) -> int: ...
    def solution_value(self) -> float: ...
    def __add__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __radd__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __sub__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __rsub__(self, other: LinearExpr | Variable | float) -> LinearExpr: ...
    def __mul__(self, coefficient: float) -> LinearExpr: ...
    def __rmul__(self, coefficient: float) -> LinearExpr: ...
    def __le__(self, other: LinearExpr | Variable | float) -> LinearConstraint: ...
    def __ge__(self, other: LinearExpr | Variable | float) -> LinearConstraint: ...

class Constraint:
    def SetCoefficient(self, variable: Variable, coefficient: float) -> None: ...
    def dual_value(self) -> float: ...

class Objective:
    def SetCoefficient(self, variable: Variable, coefficient: float) -> None: ...
    def SetMinimization(self) -> None: ...
    def SetMaximization(self) -> None: ...

type _Constraint = Constraint

class Solver:
    BASIC: ClassVar[int]
    AT_UPPER_BOUND: ClassVar[int]
    OPTIMAL: ClassVar[int]
    FEASIBLE: ClassVar[int]
    @staticmethod
    def CreateSolver(solver_id: str) -> Solver | None: ...
    @staticmethod
    def infinity() -> float: ...
    def Constraint(self, lower: float, upper: float, name: str = "") -> Constraint: ...
    def NumVar(self, lower: float, upper: float, name: str) -> Variable: ...
    def IntVar(self, lower: float, upper: float, name: str) -> Variable: ...
    def Objective(self) -> Objective: ...
    def Solve(self) -> int: ...
    def SetTimeLimit(self, milliseconds: int) -> None: ...
    def Add(self, constraint: LinearConstraint | bool, name: str = "") -> _Constraint: ...
    def Sum(self, terms: Iterable[LinearExpr | Variable | float]) -> LinearExpr: ...
    def Minimize(self, expression: LinearExpr | Variable | float) -> None: ...
